### ISSUE TITLE
Bug Report: Story Mode broken

### ISSUE THREAD

**Issue by BombasticTom** [CryBitDev/Sonic.exe-source-1.5-and-2#10]
Story mode works just fine when you launch it for the first time, but when you finish it, it won't work the same as it used to. It starts with no cutscene, no level title and it just gives you access to play the first song. After it, cutscene two plays and story mode finishes.

I guess it's an issue with the funkin.sol file? When I remove the funkin.sol file it overwrites the data and it works as normal (again, for only once)

**Comment by CryBitDev** [comment]
Literally press up and right
