### ISSUE TITLE
Game crashing on startup after compiling

### ISSUE THREAD

**Issue by AdmiralKirby** [CryBitDev/Sonic.exe-source-1.5-and-2#15]
Everytime I compile the game, it starts up. But before I get to the beginning, the program shuts off. No warning or Error, nothing in the cmd. What do I do?

Edit: Im on Windows

**Comment by CryBitDev** [comment]
What os are you on?

**Comment by AdmiralKirby** [comment]
Windows

**Comment by AdmiralKirby** [comment]
> What os are you on?

Windows, and I followed all the steps for it too

**Comment by AdmiralKirby** [comment]
I just tested on the latest stable release of Kade, works just fine. It’s this mod making it crash

**Comment by Abazoid** [comment]
It happened with me before too. I just got the windows version and deleted the source code.

**Comment by AdmiralKirby** [comment]
> It happened with me before too. I just got the windows version and deleted the source code.

I don’t want to use the already compiled version, i can’t make changes to it. (Btw I’m not doing anything malicious with the code I’m just trying to learn for myself)

**Comment by CryBitDev** [comment]
Just compile it in debug. `lime test windows -debug`

**Comment by AdmiralKirby** [comment]
> Just compile it in debug. `lime test windows -debug`

Now Im getting Null Object Reference from the console.
https://imgur.com/a/diNbVHz

**Comment by AdmiralKirby** [comment]
Why was this closed? The issue was not fixed?

**Comment by ZanderRivera** [comment]
I think this you need to update VS 2019.
![Screenshot_20221010_154757](https://user-images.githubusercontent.com/107231882/194819988-58f59696-b238-470c-94d5-6190124cd4f7.jpg)
