### ISSUE TITLE
Updated Sonic.exe flash files

### ISSUE THREAD

**Issue by sawyer400** [CryBitDev/Sonic.exe-source-1.5-and-2#17]
I wanna make sonic.exe b-side, but i cant because there is no updated Sonic.exe flash files.

**Comment by AdmiralKirby** [comment]
> I wanna make sonic.exe b-side, but i cant because there is no updated Sonic.exe flash files.

You can just use the one already there, that isn't a bug

**Comment by CryBitDev** [comment]
> I wanna make sonic.exe b-side, but i cant because there is no updated Sonic.exe flash files.

Lol no :trollface: .

**Comment by DotWith** [comment]
> > I wanna make sonic.exe b-side, but i cant because there is no updated Sonic.exe flash files.
> 
> Lol no :trollface: .

I will apply the color shader you can't stop me

**Comment by ItzEpicstickman** [comment]
why :(

> > I wanna make sonic.exe b-side, but i cant because there is no updated Sonic.exe flash files.
> 
> Lol no :trollface: .

why :(

**Comment by CrashyBoi74** [comment]
> > I wanna make sonic.exe b-side, but i cant because there is no updated Sonic.exe flash files.
> 
> You can just use the one already there, that isn't a bug

i think they probably meant that they cant use them because of the ''im gonna getcha, i am god'' animation that isnt included on the .fla included here
