### ISSUE TITLE
I am so sorry if this annoys you developers.

### ISSUE THREAD

**Issue by Abazoid** [CryBitDev/Sonic.exe-source-1.5-and-2#18]
I would really like to make an Fnf mod and I am inspired by you guys. Could you teach me how to make effects like when sonic says the HOHOHO part in too slow? I mean that red screen that shows up. Thank you.

**Comment by CryBitDev** [comment]
Find a tutorial, don't ask us 👌.

**Comment by flashintv** [comment]
this guy dude

**Comment by DotWith** [comment]
Bruh stfu with yo crusty ass hair line

**Comment by AdmiralKirby** [comment]
Why dafuq are you all out to get this guy? Ignore it, sheesh

**Comment by Abazoid** [comment]
> Why dafuq are you all out to get this guy? Ignore it, sheesh

Thanks. :) Appreciate it.
