### ISSUE TITLE
old lord x soundfont

### ISSUE THREAD

**Issue by AlyssonRo** [CryBitDev/Sonic.exe-source-1.5-and-2#19]
i can only found soundfonts from the new one

**Comment by AdmiralKirby** [comment]
There are no soundfonts?

**Comment by AlyssonRo** [comment]
> There are no soundfonts?

can be a chromatic scale too dont need to be official

**Comment by AdmiralKirby** [comment]
> > There are no soundfonts?
> 
> can be a chromatic scale too dont need to be official

There are no soundfonts here only game files. You have to make it yourself.
