### ISSUE TITLE
Enhancement: ADD SONIC.EXE V2 UPDATE ASSETS FLA FILES, SONIC.EXE PIXEL FLA FILES RIGHT NOW IN THE SOURCE CODE

### ISSUE THREAD

**Issue by ItzEpicstickman** [CryBitDev/Sonic.exe-source-1.5-and-2#21]
## What is your suggestion, and why should it be implemented?
I need to make a minus skin so please :(
here is the mod:- https://gamebanana.com/mods/318906
here is the preview of you can't run sprite:- https://twitter.com/EpiclyA/status/1468825312741888001/photo/1
now can you please add the fla files of them :(

**Comment by AdmiralKirby** [comment]
Demanding the updated sonic.exe fla in all caps just so you can recolor it is extremely rude. You made an entirely new issue from another existing issue that was already answered just so you would get your way. You are lucky to even get version 1 from this game let alone the source code. Be grateful, man.

**Comment by ItzEpicstickman** [comment]
> Demanding the updated sonic.exe fla in all caps just so you can recolor it is extremely rude. You made an entirely new issue from another existing issue that was already answered just so you would get your way. You are lucky to even get version 1 from this game let alone the source code. Be grateful, They put a lot of effort in this.

I'm very sorry, but i actually wanted the fla due to the new 'i am god' animation but, i think you're right, sorry for this :(
