### ISSUE TITLE
Enhancement: cutscenes for main story and fleetway fla and exe gf fla?

### ISSUE THREAD

**Issue by SpiderUgh** [CryBitDev/Sonic.exe-source-1.5-and-2#25]
cutscenes for main story and fleetway fla and exe gf fla?

**Comment by DotWith** [comment]
exe gf file size is too thicc to send.

**Comment by IndigoDarkw0lf** [comment]
> exe gf file size is too thicc to send.

replying almost 3 months later, can't they use google drive or mega?

**Comment by CryBitDev** [comment]
No fla's :)
