### ISSUE TITLE
I'm Getting these errors and the game crashes after i compile.

### ISSUE THREAD

**Issue by Phoneguytech75** [CryBitDev/Sonic.exe-source-1.5-and-2#27]
**Errors:**
`source/Paths.hx:147: characters 18-29 : Accessing this field requires a system platform (php,neko,cpp,etc.)`
`source/Paths.hx:149: characters 25-33 : String should be Int`
`source/MP4Handler.hx:18: characters 20-29 : Type not found : VlcBitmap`
`source/TitleState.hx:41: lines 41-562 : ... Defined in this class`
`source/OptionsMenu.hx:4: characters 8-19 : You cannot access the cpp package while targeting js (for cpp.abi.Abi)`
`source/PlayState.hx:5033: characters 40-51 : ... referenced here`

**Comment by DotWith** [comment]
html5 doesn't work.

**Comment by Phoneguytech75** [comment]
I was compiling to windows and i used vscode and these were the errors that showed on the haxe build cache.
I tried using the -debug argument and I got these errors:
`Called from polymod.backends.LimeBackend.init (polymod/backends/LimeBackend.hx line 127)`
`Called from polymod.backends.PolymodAssets.init (polymod/backends/PolymodAssets.hx line 133)`
`Called from polymod.Polymod.init (polymod/Polymod.hx line 252)`
`Called from TitleState.create (TitleState.hx line 63)`
`Called from flixel.FlxGame.switchState (flixel/FlxGame.hx line 637)`
`Called from flixel.FlxGame.create (flixel/FlxGame.hx line 360)`
`Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)`
`Called from openfl.display.DisplayObject.__dispatchEvent (openfl/display/DisplayObject.hx line 1417)`
`Called from openfl.display.DisplayObject.__dispatchWithCapture (openfl/display/DisplayObject.hx line 1478)`
`Called from openfl.display.DisplayObjectContainer.addChildAt (openfl/display/DisplayObjectContainer.hx line 266)`
`Called from openfl.display.DisplayObjectContainer.addChild (openfl/display/DisplayObjectContainer.hx line 155)`
`Called from Main.setupGame (Main.hx line 84)`
`Called from Main.init (Main.hx line 61)`
`Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)`
`Called from openfl.display.DisplayObject.__dispatchEvent (openfl/display/DisplayObject.hx line 1417)`
`Called from openfl.display.DisplayObject.__dispatchWithCapture (openfl/display/DisplayObject.hx line 1478)`
`Called from openfl.display.DisplayObjectContainer.addChildAt (openfl/display/DisplayObjectContainer.hx line 266)`
`Called from openfl.display.DisplayObjectContainer.addChild (openfl/display/DisplayObjectContainer.hx line 155)`
`Called from Main.main (Main.hx line 35)`
`Null Object Reference`
`Called from Main::main Main.hx line 35`
`Called from openfl.display.DisplayObjectContainer::addChild openfl/display/DisplayObjectContainer.hx line 155`
`Called from openfl.display.DisplayObjectContainer::addChildAt openfl/display/DisplayObjectContainer.hx line 266`
`Called from openfl.display.DisplayObject::__dispatchWithCapture openfl/display/DisplayObject.hx line 1478`
`Called from openfl.display.DisplayObject::__dispatchEvent openfl/display/DisplayObject.hx line 1417`
`Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402`
`Called from Main::init Main.hx line 61`
`Called from Main::setupGame Main.hx line 84`
`Called from openfl.display.DisplayObjectContainer::addChild openfl/display/DisplayObjectContainer.hx line 155`
`Called from openfl.display.DisplayObjectContainer::addChildAt openfl/display/DisplayObjectContainer.hx line 266`
`Called from openfl.display.DisplayObject::__dispatchWithCapture openfl/display/DisplayObject.hx line 1478`
`Called from openfl.display.DisplayObject::__dispatchEvent openfl/display/DisplayObject.hx line 1417`
`Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402`
`Called from flixel.FlxGame::create flixel/FlxGame.hx line 360`
`Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637`
`Called from TitleState::create TitleState.hx line 63`
`Called from polymod.Polymod::init polymod/Polymod.hx line 252`
`Called from polymod.backends.PolymodAssets::init polymod/backends/PolymodAssets.hx line 133`
`Called from polymod.backends.LimeBackend::init polymod/backends/LimeBackend.hx line 127`
`Error : Null Object Reference`

**Comment by DotWith** [comment]
Polymod seems to be broken.

**Comment by Phoneguytech75** [comment]
I downloaded an old version of polymod and it seemed to work.
Thanks for all the help!!

**Comment by DotWith** [comment]
> I downloaded an old version of polymod and it seemed to work. Thanks for all the help!!

I can tell you how to add polymod support... >:)
